name: Run Daily MLB Hitter Data R Script

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI
  schedule:
    # Every day at 5:35 AM ET (9:35 AM UTC)
    - cron: '35 9 * * *'

    # Every day at 12:05 PM ET (4:05 PM UTC)
    - cron: '5 16 * * *'

    # Every day at 5:35 PM ET (9:35 PM UTC)
    - cron: '35 21 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('googlesheets4', 'dplyr', 'httr', 'base64enc', 'jsonlite', 'stringi'), repos = 'https://cloud.r-project.org')"

    - name: Check installed R packages
      run: |
        Rscript -e 'cat("Loaded packages:\n"); print(.packages())'
    
    - name: Run R script
      env:
        GCP_SHEETS_KEY_B64: ${{ secrets.GCP_SHEETS_KEY_B64 }}
      run: |
        Rscript "daily pitching data.R"
