name: MLB Games Played Tracker

on:
  #schedule:
    #- cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  fetch-mlb-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr
            any::jsonlite
            any::dplyr
            any::googlesheets4
            any::base64enc
          cache: true
          cache-version: 1

      - name: Run MLB Games Played Tracker
        env:
          GCP_SHEETS_KEY_B64: ${{ secrets.GCP_SHEETS_KEY_B64 }}
          MLBGamesPlayedGOOGLE_SHEET_ID: ${{ secrets.MLBGAMESPLAYEDGOOGLE_SHEET_ID }}
        run: Rscript MLBGamesPlayedTracker.R
